# Generated by Django 4.2 on 2024-09-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_lesson_course'),
        ('users', '0003_alter_user_city_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Оплаченный курс'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.lesson', verbose_name='Оплаченный урок'),
        ),
    ]
