# Generated by Django 4.2 on 2024-10-10 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Время последнего посещения'),
        ),
    ]
